### ISSUE TITLE
Expand to all 4 parameters (including optional)

### ISSUE THREAD

**Issue by bryfry** [isaaccarjr/phoenix#2]
https://github.com/isaaccarjr/phoenix/blob/33c42d6ed185fc9cc3ebc74aec1b3f3ebdf6bcc7/SSH%20Tunneling#L19

Expand the command example to include the optional local address to listen on.

**Comment by TheAscendent** [comment]
we have reworded the document to have more consistency

**Comment by bryfry** [comment]
🎉
