### ISSUE TITLE
Expand on the remote portion of the -L flag

### ISSUE THREAD

**Issue by bryfry** [isaaccarjr/phoenix#3]
https://github.com/isaaccarjr/phoenix/blob/33c42d6ed185fc9cc3ebc74aec1b3f3ebdf6bcc7/SSH%20Tunneling#L39-L40

Expand on what this means. 
Why do you have a target address and port? 
Give multiple examples and what use-cases it would support.

E.g.: 
127.0.0.1:80
google.com:443

**Comment by TheAscendent** [comment]
has been reworded

**Comment by bryfry** [comment]
coolio
