### ISSUE TITLE
Introduction / Five W's

### ISSUE THREAD

**Issue by bryfry** [isaaccarjr/phoenix#4]
Move troubleshooting steps to another file:
https://github.com/isaaccarjr/phoenix/blob/33c42d6ed185fc9cc3ebc74aec1b3f3ebdf6bcc7/SSH%20Tunneling#L1-L14

- Add a BLUF (but dont fill it out yet, just know you will need to eventually summarize this document in a single sentence)

- Start with answering the [five w's](https://en.wikipedia.org/wiki/Five_Ws).  Specifically target your answers so that the reader will know why they should keep reading. Bullets are okay for this to start, we might adapt it into a paragraph after that.

**Comment by TheAscendent** [comment]
5 w's have been updated

**Comment by bryfry** [comment]
cool!
