### ISSUE TITLE
Expand summary of -L into a paragraph

### ISSUE THREAD

**Issue by bryfry** [isaaccarjr/phoenix#5]
https://github.com/isaaccarjr/phoenix/blob/33c42d6ed185fc9cc3ebc74aec1b3f3ebdf6bcc7/SSH%20Tunneling#L29

- Use full sentences
- Explain what -L is for and why we care to use it

**Comment by TheAscendent** [comment]
this was a section taken out of the secure shell book that is referenced. we rewrote a simpler explanation and expanded on the client/server verbiage

**Comment by bryfry** [comment]
Cool!
