### ISSUE TITLE
Explain directionality of ssh

### ISSUE THREAD

**Issue by bryfry** [isaaccarjr/phoenix#6]
These two lines explain to me that there is some directionality to ssh but this assumes the reader understands that.  Additionally, I think the backwards arrow on reverse port forwarding can cause confusion.  The connection still is from A to B but the port forward is reversed.  This is why (even if you intended to show the port forward) the directionality of your ssh connection is important to discuss.

https://github.com/isaaccarjr/phoenix/blob/33c42d6ed185fc9cc3ebc74aec1b3f3ebdf6bcc7/SSH%20Tunneling#L18
https://github.com/isaaccarjr/phoenix/blob/33c42d6ed185fc9cc3ebc74aec1b3f3ebdf6bcc7/SSH%20Tunneling#L44

Explain how ssh works with respect to directionality (ssh client, ssh server) and explain how you will diagram in all future text the directionality of the ssh connection.

**Comment by TheAscendent** [comment]
"note" sections explain this now

**Comment by bryfry** [comment]
Cool!
